# Generated by Django 4.1.4 on 2022-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publucada',
            field=models.BooleanField(default=False),
        ),
    ]
