# Generated by Django 4.1.4 on 2022-12-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publucada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publucada',
            new_name='publicada',
        ),
    ]
